"""Generate Experiment W sources from the pinned pqmx/SLOTHY checkout.

The upstream assembly uses cpp includes for twiddle tables.  This script expands
those includes and places only the code in the project's existing ITCM section,
while preserving the upstream MIT notices and its ordinary .data twiddle tables.
It also emits one deterministic forward-NTT test vector using the reference
definition from pqmx/tests/ntt-kyber/main.c.
"""

from __future__ import annotations

import subprocess
from pathlib import Path


HERE = Path(__file__).resolve().parent
TOPIC = HERE.parent
PQMX = TOPIC / "pqmx-upstream"
OPT = PQMX / "slothy" / "examples" / "opt" / "armv8m" / "kyber"
NAIVE = PQMX / "slothy" / "examples" / "naive" / "armv8m" / "kyber"
PQMX_WIP = TOPIC / "pqmx-mve-ntts"
WIP_OPT = PQMX_WIP / "slothy" / "examples" / "opt" / "armv8m" / "kyber"
WIP_NAIVE = PQMX_WIP / "slothy" / "examples" / "naive" / "armv8m" / "kyber"
OUT = HERE / "expw-src"
GCC = Path(
    r"C:\Renesas\RA\e2studio_v2026-04.2_fsp_v6.5.0"
    r"\toolchains\gcc_arm\13.2.rel1\bin\arm-none-eabi-gcc.exe"
)

PQMX_COMMIT = "89465b9756cd9b321966c99e21301b7a0a2e4de0"
SLOTHY_COMMIT = "55983e6760e98aece5359055085a7def96c688b7"
PQMX_WIP_COMMIT = "1eeaf854e60d4ac30a2866d2a05f5935199ad6a6"
SLOTHY_WIP_COMMIT = "ed3b034b3a3fbf06530784dd01a7622d4f6cf0fb"

SOURCES = (
    "ntt_kyber_1_23_45_67_opt_m85",
    "ntt_kyber_1_23_45_67_no_trans_opt_m85",
    "ntt_kyber_1_23_45_67_no_trans_vld4_opt_m85",
    "ntt_kyber_12_345_67_opt_size_m85",
    "ntt_kyber_12_345_67_opt_speed_m85",
    "intt_kyber_1_23_45_67_opt_m55",
)
WIP_SOURCES = ("intt_kyber_1_23_45_67_opt_m85",)

ZETAS = (
    -1044, -758, -359, -1517, 1493, 1422, 287, 202,
    -171, 622, 1577, 182, 962, -1202, -1474, 1468,
    573, -1325, 264, 383, -829, 1458, -1602, -130,
    -681, 1017, 732, 608, -1542, 411, -205, -1571,
    1223, 652, -552, 1015, -1293, 1491, -282, -1544,
    516, -8, -320, -666, -1618, -1162, 126, 1469,
    -853, -90, -271, 830, 107, -1421, -247, -951,
    -398, 961, -1508, -725, 448, -1065, 677, -1275,
    -1103, 430, 555, 843, -1251, 871, 1550, 105,
    422, 587, 177, -235, -291, -460, 1574, 1653,
    -246, 778, 1159, -147, -777, 1483, -602, 1119,
    -1590, 644, -872, 349, 418, 329, -156, -75,
    817, 1097, 603, 610, 1322, -1285, -1465, 384,
    -1215, -136, 1218, -1335, -874, 220, -1187, -1659,
    -1185, -1530, -1278, 794, -1510, -854, -870, 478,
    -108, -308, 996, 991, 958, -1460, 1522, 1628,
)


def preprocess(
    name: str,
    *,
    opt_dir: Path = OPT,
    naive_dir: Path = NAIVE,
    pqmx_commit: str = PQMX_COMMIT,
    slothy_commit: str = SLOTHY_COMMIT,
) -> None:
    source = opt_dir / f"{name}.s"
    cmd = [
        str(GCC),
        "-E",
        "-P",
        "-C",
        "-x",
        "assembler-with-cpp",
        "-I",
        str(opt_dir),
        "-I",
        str(naive_dir),
        str(source),
    ]
    text = subprocess.check_output(cmd, text=True, encoding="utf-8")
    marker = "\n.text\n"
    if text.count(marker) != 1:
        raise RuntimeError(f"expected one .text directive in {source}")
    text = text.replace(
        marker,
        '\n.section .itcm_code_from_flash, "ax", %progbits\n',
        1,
    )
    notice = (
        f"// Generated by gen_exp_w.py from pqmx {pqmx_commit}\n"
        f"// and its pinned SLOTHY submodule {slothy_commit}.\n"
        "// Upstream source and this generated derivative are MIT licensed;\n"
        "// the full upstream copyright/license notice follows.\n"
    )
    (OUT / f"expw_{name}.s").write_text(notice + text, encoding="utf-8", newline="\n")


def bit_reverse(value: int, width: int) -> int:
    out = 0
    for _ in range(width):
        out = (out << 1) | (value & 1)
        value >>= 1
    return out


def reference_ntt(source: list[int]) -> list[int]:
    """Exact mathematical reference used by pqmx's ntt-kyber test."""
    q = 3329
    roots = [pow(17, i, q) for i in range(256)]
    result = [0] * 256
    for parity in range(2):
        for i in range(128):
            multiplier = bit_reverse(i + 128, 8) * 2
            acc = 0
            for j in range(128):
                exponent = ((multiplier * j) % 512) // 2
                acc = (acc + source[2 * j + parity] * roots[exponent]) % q
            result[2 * i + parity] = acc
    return result


def standard_ntt(source: list[int]) -> list[int]:
    """Modulo-q form of pqmx mve-ntts/tests/ntt-kyber/ntt_ref.c."""
    q = 3329
    r_inv = pow(1 << 16, -1, q)
    result = source.copy()
    k = 1
    length = 128
    while length >= 2:
        start = 0
        while start < 256:
            zeta = (ZETAS[k] * r_inv) % q
            k += 1
            for j in range(start, start + length):
                product = zeta * result[j + length] % q
                low = result[j]
                result[j + length] = (low - product) % q
                result[j] = (low + product) % q
            start += 2 * length
        length //= 2
    return result


def standard_invntt(source: list[int]) -> list[int]:
    """Modulo-q invntt_tomont reference from pqmx mve-ntts branch."""
    q = 3329
    r_inv = pow(1 << 16, -1, q)
    result = source.copy()
    k = 127
    length = 2
    while length <= 128:
        start = 0
        while start < 256:
            zeta = (ZETAS[k] * r_inv) % q
            k -= 1
            for j in range(start, start + length):
                low = result[j]
                high = result[j + length]
                result[j] = (low + high) % q
                result[j + length] = ((high - low) * zeta) % q
            start += 2 * length
        length *= 2
    final_factor = (1441 * r_inv) % q
    return [(value * final_factor) % q for value in result]


def rev4(values: list[int]) -> list[int]:
    """pqmx buf_bitrev_4: transpose each 4x4 block of int32 coefficient pairs."""
    pairs = [(values[2 * i], values[2 * i + 1]) for i in range(128)]
    for base in range(0, 128, 16):
        block = pairs[base : base + 16]
        for row in range(4):
            for col in range(4):
                pairs[base + row * 4 + col] = block[col * 4 + row]
    return [coefficient for pair in pairs for coefficient in pair]


def c_array(name: str, values: list[int]) -> str:
    rows = []
    for start in range(0, len(values), 16):
        rows.append("    " + ", ".join(str(x) for x in values[start : start + 16]))
    return (
        f"static const int16_t {name}[256] __attribute__((aligned(16))) = {{\n"
        + ",\n".join(rows)
        + "\n};\n"
    )


def write_vectors() -> None:
    source = [((i * i) + (17 * i) + 3) % 3329 for i in range(256)]
    forward = reference_ntt(source)
    if forward != standard_ntt(source):
        raise RuntimeError("direct and standard forward NTT references disagree")
    expected = rev4(forward)
    expected_inverse = standard_invntt(source)
    header = (
        "/* Generated by gen_exp_w.py from the pqmx ntt-kyber reference. */\n"
        "#ifndef EXPW_VECTORS_H\n#define EXPW_VECTORS_H\n\n"
        + c_array("expw_input", source)
        + "\n"
        + c_array("expw_expected_rev4", expected)
        + "\n"
        + c_array("expw_expected_inverse", expected_inverse)
        + "\n#endif\n"
    )
    (OUT / "expw_vectors.h").write_text(header, encoding="utf-8", newline="\n")


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for name in SOURCES:
        preprocess(name)
    for name in WIP_SOURCES:
        preprocess(
            name,
            opt_dir=WIP_OPT,
            naive_dir=WIP_NAIVE,
            pqmx_commit=PQMX_WIP_COMMIT,
            slothy_commit=SLOTHY_WIP_COMMIT,
        )
    write_vectors()
    total = len(SOURCES) + len(WIP_SOURCES)
    print(f"generated {total} assembly files and expw_vectors.h in {OUT}")


if __name__ == "__main__":
    main()
