"""Generate the Experiment Y M85 inverse variant for Plantard pointwise input."""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

from verify_exp_y_domain import run_all


HERE = Path(__file__).resolve().parent
TOPIC = HERE.parent
PQMX_WIP = TOPIC / "pqmx-mve-ntts"
SLOTHY_WIP = PQMX_WIP / "slothy"
OPT = SLOTHY_WIP / "examples" / "opt" / "armv8m" / "kyber"
NAIVE = SLOTHY_WIP / "examples" / "naive" / "armv8m" / "kyber"
OUT = HERE / "expy-src"
GCC = Path(
    r"C:\Renesas\RA\e2studio_v2026-04.2_fsp_v6.5.0"
    r"\toolchains\gcc_arm\13.2.rel1\bin\arm-none-eabi-gcc.exe"
)

PQMX_WIP_COMMIT = "1eeaf854e60d4ac30a2866d2a05f5935199ad6a6"
SLOTHY_WIP_COMMIT = "ed3b034b3a3fbf06530784dd01a7622d4f6cf0fb"
SOURCE_SYMBOL = "intt_kyber_1_23_45_67_opt_m85"
OUTPUT_SYMBOL = "intt_kyber_1_23_45_67_opt_m85_plantard"


def git_head(repository: Path) -> str:
    command = [
        "git",
        "-c",
        f"safe.directory={repository}",
        "-C",
        str(repository),
        "rev-parse",
        "HEAD",
    ]
    return subprocess.check_output(command, text=True, encoding="ascii").strip()


def preprocess_source() -> str:
    source = OPT / f"{SOURCE_SYMBOL}.s"
    command = [
        str(GCC), "-E", "-P", "-C", "-x", "assembler-with-cpp",
        "-I", str(OPT), "-I", str(NAIVE), str(source),
    ]
    return subprocess.check_output(command, text=True, encoding="utf-8")


def make_variant(source: str) -> str:
    roots_label = ".data\nroots_inv:"
    if source.count(roots_label) != 1:
        raise RuntimeError("unexpected inverse-root table declaration")
    source = source.replace(roots_label, ".data\n.balign 16\nroots_inv:", 1)

    text_marker = "\n.text\n"
    if source.count(text_marker) != 1:
        raise RuntimeError("expected exactly one .text directive")
    source = source.replace(
        text_marker, '\n.section .itcm_code_from_flash, "ax", %progbits\n', 1
    )

    if source.count(SOURCE_SYMBOL) != 3:
        raise RuntimeError("unexpected function-symbol occurrence count")
    source = source.replace(SOURCE_SYMBOL, OUTPUT_SYMBOL)

    old_scale = "        movw scaling_factor, #512"
    old_twisted = "        movw scaling_factor_twisted, #5040"
    if source.count(old_scale) != 1 or source.count(old_twisted) != 1:
        raise RuntimeError("upstream scaling prologue changed")
    source = source.replace(
        "        // ninv = 512 (scaling factor 1/128 and Montgomery factor 2^16)\n"
        + old_scale,
        "        // P/128 = 1888: cancels current Plantard pointwise factor P^-1\n"
        "        // where P = -2^32 mod 3329. Verified by verify_exp_y_domain.py.\n"
        "        movw scaling_factor, #1888",
        1,
    )
    source = source.replace(
        "        // ninv_tw = 5040 (Barrett multiplication factor)\n"
        + old_twisted,
        "        // round((P/128) * 2^15 / 3329) = 18584\n"
        "        movw scaling_factor_twisted, #18584",
        1,
    )

    function_label = f"{OUTPUT_SYMBOL}:"
    if source.count(function_label) != 1:
        raise RuntimeError("generated function label is not unique")
    source = source.replace(function_label, f".balign 16\n{function_label}", 1)

    notice = (
        f"// Generated by gen_exp_y.py from pqmx {PQMX_WIP_COMMIT}\n"
        f"// and its pinned SLOTHY submodule {SLOTHY_WIP_COMMIT}.\n"
        "// Experiment Y changes only the exported symbol, 16-byte function/root\n"
        "// alignment, and inverse prologue scale 512/5040 -> 1888/18584.\n"
        "// Upstream source and this derivative are MIT licensed; the full\n"
        "// upstream copyright/license notice follows.\n"
    )
    return notice + source


def main() -> None:
    if git_head(PQMX_WIP) != PQMX_WIP_COMMIT:
        raise RuntimeError("pqmx WIP checkout is not at the pinned commit")
    if git_head(SLOTHY_WIP) != SLOTHY_WIP_COMMIT:
        raise RuntimeError("SLOTHY WIP checkout is not at the pinned commit")
    if not GCC.is_file():
        raise RuntimeError(f"Arm GCC not found: {GCC}")

    oracle_result = run_all()
    variant = make_variant(preprocess_source())

    OUT.mkdir(parents=True, exist_ok=True)
    assembly_path = OUT / f"expy_{OUTPUT_SYMBOL}.s"
    result_path = OUT / "expy_domain_oracle_result.json"
    assembly_path.write_text(variant, encoding="utf-8", newline="\n")
    result_path.write_text(
        json.dumps(oracle_result, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    print(f"generated {assembly_path}")
    print(f"oracle {oracle_result['status']}: {result_path}")


if __name__ == "__main__":
    main()
