"""Extract vector 1 from the official X-Wing draft-10 text as C arrays."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import re


EXPECTED_LENGTHS = {
    "seed": 32,
    "sk": 32,
    "pk": 1216,
    "eseed": 64,
    "ct": 1120,
    "ss": 32,
}


def first_vector(text: str) -> dict[str, bytes]:
    appendix = text.index("Appendix C.  Test vectors")
    lines = text[appendix:].splitlines()
    fields: dict[str, str] = {}
    current: str | None = None

    for source in lines:
        line = source.strip()
        inline = re.fullmatch(r"(seed|sk|ss)\s+([0-9a-f]+)", line)
        if inline:
            name, value = inline.groups()
            if name == "seed" and fields:
                break
            fields[name] = value
            current = None
            if name == "ss":
                break
            continue
        if line in {"pk", "eseed", "ct"}:
            current = line
            fields[current] = ""
            continue
        if current is not None and re.fullmatch(r"[0-9a-f]+", line):
            fields[current] += line

    missing = set(EXPECTED_LENGTHS) - set(fields)
    if missing:
        raise ValueError(f"missing vector fields: {sorted(missing)}")

    result = {name: bytes.fromhex(value) for name, value in fields.items()}
    for name, expected in EXPECTED_LENGTHS.items():
        actual = len(result[name])
        if actual != expected:
            raise ValueError(f"{name}: {actual} bytes, expected {expected}")
    if result["seed"] != result["sk"]:
        raise ValueError("vector 1 seed/sk mismatch")
    return result


def c_array(name: str, data: bytes) -> str:
    rows = []
    for offset in range(0, len(data), 16):
        chunk = data[offset : offset + 16]
        rows.append("    " + ",".join(f"0x{byte:02x}" for byte in chunk) + ",")
    return f"static const uint8_t {name}[{len(data)}] = {{\n" + "\n".join(rows) + "\n};\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("draft", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    raw = args.draft.read_bytes()
    vector = first_vector(raw.decode("utf-8"))
    digest = hashlib.sha256(raw).hexdigest()
    generated = (
        "/* Generated by generate_d10_kat.py from\n"
        " * draft-connolly-cfrg-xwing-kem-10.txt, Appendix C, vector 1.\n"
        f" * source SHA-256: {digest}\n"
        " */\n\n"
        + c_array("d10kat_seed", vector["seed"])
        + "\n"
        + c_array("d10kat_eseed", vector["eseed"])
        + "\n"
        + c_array("d10kat_ss", vector["ss"])
        + "\n"
        + c_array("d10kat_pk", vector["pk"])
        + "\n"
        + c_array("d10kat_ct", vector["ct"])
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generated, encoding="utf-8", newline="\n")
    print(
        f"PASS source_sha256={digest} pk={len(vector['pk'])} "
        f"ct={len(vector['ct'])} output={args.output}"
    )


if __name__ == "__main__":
    main()
