"""Generate x4-only matacc assembly with a three-block rejection buffer.

The scalar functions and their 168-byte buffers remain untouched.  This file
is deliberately mechanical: clone the six public entry points with an _x4
suffix and change only the buffer-end constant used by third_if.
"""

from pathlib import Path
import sys


NAMES = (
    "matacc_asm_cache_16_32",
    "matacc_asm_cache_32_32",
    "matacc_asm_cache_32_16",
    "matacc_asm_opt_16_32",
    "matacc_asm_opt_32_32",
    "matacc_asm_opt_32_16",
)


def main() -> int:
    if len(sys.argv) != 3:
        raise SystemExit("usage: gen_expDA_matacc_x4.py INPUT.S OUTPUT.S")
    source = Path(sys.argv[1])
    output = Path(sys.argv[2])
    text = source.read_text(encoding="utf-8").lstrip("\ufeff")
    needle = "add \\tmp, #168 // XOF_BLOCKBYTES=168"
    if text.count(needle) != 1:
        raise SystemExit(f"expected one buffer-bound marker, found {text.count(needle)}")
    text = text.replace(needle, "add \\tmp, #504 // 3 * XOF_BLOCKBYTES")
    for name in NAMES:
        text = text.replace(name, name + "_x4")
    output.write_text(
        "/* Generated by gen_expDA_matacc_x4.py; do not edit by hand. */\n" + text,
        encoding="utf-8",
        newline="\n",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
