/* mul256 straight-line branchless - for zipper stitching */
#include <stdint.h>
void MULNAME(uint32_t r[16], const uint32_t a[8], const uint32_t b[8])
{
    uint64_t acc = 0, p; uint32_t hi = 0;
    p = (uint64_t)a[0] * b[0]; hi += __builtin_add_overflow(acc, p, &acc);
    r[0] = (uint32_t)acc; acc = (acc >> 32) | ((uint64_t)hi << 32); hi = 0;
    p = (uint64_t)a[0] * b[1]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[1] * b[0]; hi += __builtin_add_overflow(acc, p, &acc);
    r[1] = (uint32_t)acc; acc = (acc >> 32) | ((uint64_t)hi << 32); hi = 0;
    p = (uint64_t)a[0] * b[2]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[1] * b[1]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[2] * b[0]; hi += __builtin_add_overflow(acc, p, &acc);
    r[2] = (uint32_t)acc; acc = (acc >> 32) | ((uint64_t)hi << 32); hi = 0;
    p = (uint64_t)a[0] * b[3]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[1] * b[2]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[2] * b[1]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[3] * b[0]; hi += __builtin_add_overflow(acc, p, &acc);
    r[3] = (uint32_t)acc; acc = (acc >> 32) | ((uint64_t)hi << 32); hi = 0;
    p = (uint64_t)a[0] * b[4]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[1] * b[3]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[2] * b[2]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[3] * b[1]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[4] * b[0]; hi += __builtin_add_overflow(acc, p, &acc);
    r[4] = (uint32_t)acc; acc = (acc >> 32) | ((uint64_t)hi << 32); hi = 0;
    p = (uint64_t)a[0] * b[5]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[1] * b[4]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[2] * b[3]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[3] * b[2]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[4] * b[1]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[5] * b[0]; hi += __builtin_add_overflow(acc, p, &acc);
    r[5] = (uint32_t)acc; acc = (acc >> 32) | ((uint64_t)hi << 32); hi = 0;
    p = (uint64_t)a[0] * b[6]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[1] * b[5]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[2] * b[4]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[3] * b[3]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[4] * b[2]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[5] * b[1]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[6] * b[0]; hi += __builtin_add_overflow(acc, p, &acc);
    r[6] = (uint32_t)acc; acc = (acc >> 32) | ((uint64_t)hi << 32); hi = 0;
    p = (uint64_t)a[0] * b[7]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[1] * b[6]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[2] * b[5]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[3] * b[4]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[4] * b[3]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[5] * b[2]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[6] * b[1]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[7] * b[0]; hi += __builtin_add_overflow(acc, p, &acc);
    r[7] = (uint32_t)acc; acc = (acc >> 32) | ((uint64_t)hi << 32); hi = 0;
    p = (uint64_t)a[1] * b[7]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[2] * b[6]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[3] * b[5]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[4] * b[4]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[5] * b[3]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[6] * b[2]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[7] * b[1]; hi += __builtin_add_overflow(acc, p, &acc);
    r[8] = (uint32_t)acc; acc = (acc >> 32) | ((uint64_t)hi << 32); hi = 0;
    p = (uint64_t)a[2] * b[7]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[3] * b[6]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[4] * b[5]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[5] * b[4]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[6] * b[3]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[7] * b[2]; hi += __builtin_add_overflow(acc, p, &acc);
    r[9] = (uint32_t)acc; acc = (acc >> 32) | ((uint64_t)hi << 32); hi = 0;
    p = (uint64_t)a[3] * b[7]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[4] * b[6]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[5] * b[5]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[6] * b[4]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[7] * b[3]; hi += __builtin_add_overflow(acc, p, &acc);
    r[10] = (uint32_t)acc; acc = (acc >> 32) | ((uint64_t)hi << 32); hi = 0;
    p = (uint64_t)a[4] * b[7]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[5] * b[6]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[6] * b[5]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[7] * b[4]; hi += __builtin_add_overflow(acc, p, &acc);
    r[11] = (uint32_t)acc; acc = (acc >> 32) | ((uint64_t)hi << 32); hi = 0;
    p = (uint64_t)a[5] * b[7]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[6] * b[6]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[7] * b[5]; hi += __builtin_add_overflow(acc, p, &acc);
    r[12] = (uint32_t)acc; acc = (acc >> 32) | ((uint64_t)hi << 32); hi = 0;
    p = (uint64_t)a[6] * b[7]; hi += __builtin_add_overflow(acc, p, &acc);
    p = (uint64_t)a[7] * b[6]; hi += __builtin_add_overflow(acc, p, &acc);
    r[13] = (uint32_t)acc; acc = (acc >> 32) | ((uint64_t)hi << 32); hi = 0;
    p = (uint64_t)a[7] * b[7]; hi += __builtin_add_overflow(acc, p, &acc);
    r[14] = (uint32_t)acc; acc = (acc >> 32) | ((uint64_t)hi << 32); hi = 0;
    r[15] = (uint32_t)acc;
}